title: Zenbeard
email: alexey.yanovski1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/zenbeard" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:  lexi89

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "default-posts"
            permalink: /:categories/:title
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
