title: Zenbeard
email: alexey.yanovski1@gmail.com
description: Zen. For men.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.zenbeard.com" # the base hostname & protocol for your site
twitter_username:
github_username:  lexi89

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "default-posts"
            permalink: /:categories/:title
gems: [jekyll-paginate]
paginate: 8
paginate_path: "/page:num/"
